cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    s3:
      bucket: heybit-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false