spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

app:
  frontend:
    base-url: ${FRONTEND_BASE_URL:http://localhost:3000}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
