server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:thisisaverylongsecretkeyforjwttoken123456789012345678901234567890}

app:
  frontend:
    base-url: ${FRONTEND_BASE_URL:http://localhost:3000}

spring:
  application:
    name: heybit-backend

  profiles:
    include: oauth, aws

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  quartz:
    job-store-type: memory
    scheduler:
      instance-name: heybitScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          threadPool:
            threadCount: 5
          jobStore:
            misfireThreshold: 60000

springdoc:
  api-docs:
    enabled: true       # OpenAPI 문서 활성화
  swagger-ui:
    enabled: true       #Swagger UI 사용 여부
    path: /swagger-ui.html  # Swagger 접속 경로 지정
  override-with-generic-response: false  # 자동 응답 포맷 생성 비활성화