server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:thisisaverylongsecretkeyforjwttoken123456789012345678901234567890}

spring:
  application:
    name: heybit-backend

  profiles:
    include: oauth

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console




