spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
  
  config:
    import: optional:file:.env.local[.properties]

  quartz:
    job-store-type: memory
    scheduler:
      instance-name: heybitScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          threadPool:
            threadCount: 5
          jobStore:
            misfireThreshold: 60000

app:
  frontend:
    base-url: ${FRONTEND_BASE_URL:http://localhost:3000}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
