spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            scope: account_email
            authorization-grant-type: authorization_code
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
          google:
            client-secret: ${GOOGLE_CLIENT_SECRET}
            client-id: ${GOOGLE_CLIENT_ID}
            scope: profile,email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
